# langauge supported
language: python
# python version
python:
  - 3.6

install:
  - pip install -r requirements.txt

services:
  # start postgres service
  - postgresql

before_script:
  # create a testing database for running tests
  - psql -c 'create database store_test;' -U postgres

  # set up env file to be use by the app
  - cp .env.example .env

script:
  #  run tests
  - coverage run --ignore=venv -m pytest && coverage report

after_success:
  # coverage report
  - coveralls 